spring:
    datasource:
      url: "jdbc:mysql://192.168.254.131:3306/organizations?useSSL=true&serverTimezone=UTC"
      username: "testuser"
      password: "19811981"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://140.143.45.252:8761/eureka

#eureka.instance.prefer-ip-address: true
#eureka.client.fetch-registry: true
#eureka.client.register-with-eureka: true
#eureka.client.service-url.defaultZone: http://140.143.45.252:8761/eureka/
